In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy.random as nr

In [2]:
# Importing the dataset
dataset = pd.read_csv('BD.csv')

In [ ]:
dataset.head()

In [ ]:
dataset.shape

In [3]:
dataset.drop(['Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18' , 'Unnamed: 19'], axis=1, inplace=True)

In [ ]:
dataset.head()

In [ ]:
dataset.info

In [4]:
dataset.drop(dataset.index[204], inplace=True)

In [5]:
dataset['Profit'].fillna(dataset['Profit'].mean(), inplace=True)

In [ ]:
dataset.info

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 15].values

In [ ]:
X

In [16]:
y

array([249804.     , 277324.     , 250187.     , 290215.     ,
       279912.     , 304595.     , 246935.     , 214585.     ,
       189148.     , 209188.     , 237523.     , 221145.     ,
       249249.     , 273868.     , 251632.     , 296459.     ,
       294667.     , 322492.     , 269174.     , 252207.     ,
       231370.     , 246049.     , 275110.     , 283340.     ,
       313837.     , 343298.     , 309663.     , 337883.     ,
       338418.     , 387189.     , 315563.     , 301117.     ,
       278569.     , 289490.     , 322139.     , 317410.     ,
       340207.     , 372200.     , 341494.     , 379729.     ,
       375994.     , 425121.     , 367092.     , 341469.     ,
       317775.     , 344915.     , 377252.     , 361582.     ,
       402909.     , 433434.     , 382629.     , 422068.     ,
       452293.     , 460802.     , 396937.     , 372935.     ,
       338681.     , 356022.     , 378526.     , 365387.     ,
       404909.     , 391343.     , 354301.     , 395059

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

In [8]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
y_test

array([269174.     , 344915.     , 289490.     , 372200.     ,
       478209.     , 397647.     , 304595.     , 520192.     ,
       249249.     , 521698.     , 391343.     , 549991.     ,
       556382.     , 651839.     , 512789.     , 214585.     ,
       430444.     , 446514.     , 385942.     , 370159.     ,
       317775.     , 500485.     , 395059.     , 534811.     ,
       350890.     , 482223.     , 473145.     , 608343.     ,
       694358.     , 444923.     , 431660.28125, 404909.     ,
       294667.     , 359599.     , 347529.     , 275110.     ,
       327475.     , 465251.     , 279912.     , 608216.     ,
       564710.     ])

In [10]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [14]:
y_pred

array([320648.44502963, 342487.58534492, 306502.25223397, 310015.51204043,
       417396.65815526, 428029.59114446, 294766.61771717, 495750.23587544,
       294846.50687688, 517692.22184043, 352546.61867159, 557232.73005069,
       510804.88201109, 519829.62322418, 489564.74583888, 305094.55427741,
       469425.36629602, 469403.59697064, 423253.59737076, 377759.11326141,
       343313.84066009, 459424.97811209, 389042.05017117, 511153.91807354,
       372491.39961717, 485064.64236707, 569657.40299287, 498175.59014274,
       534567.33442023, 387903.11792909, 576784.74308547, 353960.7974473 ,
       337513.77527183, 352043.83199726, 378506.54867058, 310567.46981744,
       352526.26825088, 387739.32668208, 322806.38389152, 534444.34456166,
       450838.4276012 ])

In [18]:
forecast_error = y_test - y_pred

In [19]:
forecast_error

array([ -51474.44502963,    2427.41465508,  -17012.25223397,
         62184.48795957,   60812.34184474,  -30382.59114446,
          9828.38228283,   24441.76412456,  -45597.50687688,
          4005.77815957,   38796.38132841,   -7241.73005069,
         45577.11798891,  132009.37677582,   23224.25416112,
        -90509.55427741,  -38981.36629602,  -22889.59697064,
        -37311.59737076,   -7600.11326141,  -25538.84066009,
         41060.02188791,    6016.94982883,   23657.08192646,
        -21601.39961717,   -2841.64236707,  -96512.40299287,
        110167.40985726,  159790.66557977,   57019.88207091,
       -145124.46183547,   50948.2025527 ,  -42846.77527183,
          7555.16800274,  -30977.54867058,  -35457.46981744,
        -25051.26825088,   77511.67331792,  -42894.38389152,
         73771.65543834,  113871.5723988 ])