In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy.random as nr

In [2]:
# Importing the dataset
dataset = pd.read_csv('BD.csv')

In [ ]:
dataset.head()

In [ ]:
dataset.shape

In [3]:
dataset.drop(['Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18' , 'Unnamed: 19'], axis=1, inplace=True)

In [ ]:
dataset.head()

In [ ]:
dataset.info

In [4]:
dataset.drop(dataset.index[204], inplace=True)

In [5]:
dataset['Profit'].fillna(dataset['Profit'].mean(), inplace=True)

In [ ]:
dataset.info

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 15].values

In [ ]:
X

In [ ]:
y

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
y_test

array([269174.     , 344915.     , 289490.     , 372200.     ,
       478209.     , 397647.     , 304595.     , 520192.     ,
       249249.     , 521698.     , 391343.     , 549991.     ,
       556382.     , 651839.     , 512789.     , 214585.     ,
       430444.     , 446514.     , 385942.     , 370159.     ,
       317775.     , 500485.     , 395059.     , 534811.     ,
       350890.     , 482223.     , 473145.     , 608343.     ,
       694358.     , 444923.     , 431660.28125, 404909.     ,
       294667.     , 359599.     , 347529.     , 275110.     ,
       327475.     , 465251.     , 279912.     , 608216.     ,
       564710.     ])

In [9]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [10]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

C:\Users\Anthony\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [11]:
y_pred

array([189148.     , 189148.     , 189148.     , 189148.     ,
       189148.     , 189148.     , 189148.     , 189148.     ,
       189148.     , 189148.     , 189148.     , 431660.28125,
       431660.28125, 189148.     , 189148.     , 189148.     ,
       189148.     , 189148.     , 189148.     , 189148.     ,
       189148.     , 189148.     , 189148.     , 189148.     ,
       189148.     , 189148.     , 431660.28125, 431660.28125,
       189148.     , 189148.     , 431660.28125, 189148.     ,
       189148.     , 189148.     , 189148.     , 189148.     ,
       189148.     , 189148.     , 189148.     , 189148.     ,
       189148.     ])

In [12]:
forecast_error = y_test - y_pred

In [13]:
forecast_error

array([ 80026.     , 155767.     , 100342.     , 183052.     ,
       289061.     , 208499.     , 115447.     , 331044.     ,
        60101.     , 332550.     , 202195.     , 118330.71875,
       124721.71875, 462691.     , 323641.     ,  25437.     ,
       241296.     , 257366.     , 196794.     , 181011.     ,
       128627.     , 311337.     , 205911.     , 345663.     ,
       161742.     , 293075.     ,  41484.71875, 176682.71875,
       505210.     , 255775.     ,      0.     , 215761.     ,
       105519.     , 170451.     , 158381.     ,  85962.     ,
       138327.     , 276103.     ,  90764.     , 419068.     ,
       375562.     ])

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

ValueError: continuous is not supported

In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
accuracies.mean()
accuracies.std()